#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause
"""
Cara dath font generator — host-side tool.

Reads a TrueType / OpenType font, rasterises each codepoint in a
contiguous range at the requested pixel size, thresholds the result
to 1-bit, and emits a C source file in the same shape as
src/croi/dath/font_8x8.c — one byte per row, MSB the leftmost pixel,
laid out for the DathFont struct that src/croi/dath/text.c consumes.

This script bridges three font paths in dath:

  1. The hand-coded src/croi/dath/font_8x8.c (canonical placeholder).
  2. Output from this generator pointed at an OpenType remake of
     the AmigaDOS Topaz font (intermediate; preferred over hand
     editing once a suitable input is selected).
  3. The Phase 7 TrueType loader, which renders glyphs at runtime
     from a .ttf bundled at link time. That work obsoletes both
     this generator and the hand-coded fallback.

Recommended source fonts (none shipped — pick one yourself, mind the
license; we expect BSD-2-Clause / CC0 / public-domain inputs only):

  * Topaz / Topaz Plus by Bert Govaerts — Amiga ROM font remade as
    TTF. Several free downloads exist on font archives.
  * Amiga4ever by ck — Topaz-inspired pixel font.
  * Pixel Operator by Jayvee Enaguas — generic 8x8/8x16 pixel font,
    CC0 on the author's site.

Dependencies:

    pip install Pillow

Example invocation (regenerate the 8x8 font in place):

    ./tools/font-gen/font_gen.py \\
        --font ~/Library/Fonts/Topaz.ttf \\
        --size 8 \\
        --first 0x20 --last 0x7A \\
        --name dath_font_8x8 \\
        --output src/croi/dath/font_8x8.c
"""

import argparse
import datetime
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.stderr.write(
        "error: requires Pillow (PIL fork).\n"
        "       install with: pip install Pillow\n"
    )
    sys.exit(2)


def render_glyph(font, ch, width, height, threshold):
    """Render `ch` into a width x height grid; return list of `height`
    bytes, MSB the leftmost pixel of each row."""
    img = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(img)

    # Position the glyph: align the typographic origin to (0, baseline)
    # by undoing the font's bounding-box offset on each axis.
    try:
        bbox = font.getbbox(ch)
    except (TypeError, ValueError):
        bbox = None

    if bbox is not None:
        x_off = -bbox[0]
        y_off = -bbox[1]
        bbox_h = bbox[3] - bbox[1]
        # Centre vertically when the glyph is shorter than the cell so
        # ascenders/descenders don't clip.
        if 0 < bbox_h < height:
            y_off += (height - bbox_h) // 2
    else:
        x_off, y_off = 0, 0

    draw.text((x_off, y_off), ch, fill=255, font=font)

    rows = []
    for y in range(height):
        b = 0
        for x in range(width):
            if img.getpixel((x, y)) >= threshold:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows


def emit_c(out_path, name, source_path, width, height, first, last, glyphs):
    """Write the C source. Matches the layout of src/croi/dath/font_8x8.c."""
    n_glyphs = last - first + 1
    today = datetime.date.today().isoformat()
    src_basename = Path(source_path).name

    out = []
    out.append("// SPDX-License-Identifier: BSD-2-Clause")
    out.append("//")
    out.append(f"// Auto-generated by tools/font-gen/font_gen.py on {today}.")
    out.append("//")
    out.append("// DO NOT EDIT BY HAND — regenerate via the script.")
    out.append("//")
    out.append("// The hand-coded fallback at src/croi/dath/font_8x8.c is")
    out.append("// the canonical placeholder until the Phase 7 TrueType loader")
    out.append("// supersedes both paths.")
    out.append("//")
    out.append(f"// Source font: {src_basename}")
    out.append(f"// Codepoints:  0x{first:02X}..0x{last:02X} ({n_glyphs} glyphs)")
    out.append(f"// Cell size:   {width}x{height} pixels")
    out.append("")
    out.append("#include <cara/dath.h>")
    out.append("#include <cara/types.h>")
    out.append("")
    out.append(f"static const u8 {name}_glyphs[{n_glyphs} * {height}] = {{")
    for cp in range(first, last + 1):
        rows = glyphs[cp - first]
        bytes_str = ", ".join(f"0x{b:02X}" for b in rows)
        # ASCII printable as inline comment; everything else gets a hex tag.
        if 0x20 < cp < 0x7F:
            label = f"0x{cp:02X} '{chr(cp)}'"
        else:
            label = f"0x{cp:02X}"
        out.append(f"    {bytes_str},  // {label}")
    out.append("};")
    out.append("")
    out.append(f"const struct DathFont {name} = {{")
    out.append(f"    .width = {width},")
    out.append(f"    .height = {height},")
    out.append(f"    .first_glyph = 0x{first:02X},")
    out.append(f"    .last_glyph = 0x{last:02X},")
    out.append(f"    .bitmap = {name}_glyphs,")
    out.append("};")
    out.append("")

    Path(out_path).write_text("\n".join(out))
    return n_glyphs


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--font", required=True, help="path to TTF/OTF font file")
    ap.add_argument(
        "--size",
        type=int,
        required=True,
        help="PIL font size — typically equals --height for pixel fonts",
    )
    ap.add_argument(
        "--width", type=int, default=8, help="glyph width in pixels (≤ 8)"
    )
    ap.add_argument(
        "--height", type=int, default=8, help="glyph height in pixels"
    )
    ap.add_argument(
        "--first",
        type=lambda s: int(s, 0),
        default=0x20,
        help="first codepoint (default 0x20)",
    )
    ap.add_argument(
        "--last",
        type=lambda s: int(s, 0),
        default=0x7A,
        help="last codepoint inclusive (default 0x7A)",
    )
    ap.add_argument(
        "--name",
        default="dath_font_8x8",
        help="emitted DathFont symbol name",
    )
    ap.add_argument(
        "--threshold",
        type=int,
        default=128,
        help="alpha threshold for set vs clear (0..255, default 128)",
    )
    ap.add_argument("--output", required=True, help="output C source path")
    args = ap.parse_args()

    if args.width <= 0 or args.width > 8:
        sys.stderr.write(
            "error: --width must be 1..8 (Tier 1 dath stores one row per byte)\n"
        )
        sys.exit(2)
    if args.height <= 0:
        sys.stderr.write("error: --height must be positive\n")
        sys.exit(2)
    if args.first < 0 or args.last < args.first or args.last > 0xFFFF:
        sys.stderr.write("error: bad codepoint range\n")
        sys.exit(2)

    try:
        font = ImageFont.truetype(args.font, size=args.size)
    except OSError as e:
        sys.stderr.write(f"error: cannot open font {args.font}: {e}\n")
        sys.exit(2)

    glyphs = []
    for cp in range(args.first, args.last + 1):
        glyphs.append(
            render_glyph(font, chr(cp), args.width, args.height, args.threshold)
        )

    n = emit_c(
        args.output,
        args.name,
        args.font,
        args.width,
        args.height,
        args.first,
        args.last,
        glyphs,
    )
    sys.stdout.write(f"wrote {n} glyphs to {args.output}\n")


if __name__ == "__main__":
    main()
