// SPDX-License-Identifier: BSD-2-Clause
// AUTOGENERATED by tools/lvo-gen from sample.conf — <lib>/lvo.h ordinal & canonical-LVO constants.
// Do not edit; regenerate with `make`. Source of truth:
// tools/lvo-gen/sample.conf and docs/LVO.md.

#ifndef SAMPLE_LVO_H
#define SAMPLE_LVO_H

// CaraOS runtime ordinals — declaration order in sample.conf.
// These are what the inline stubs in <proto/sample.h> use to
// index into the negative-side function-pointer table.
constexpr int CARA_IDX_LIB_OPEN                         =    0;
constexpr int CARA_IDX_LIB_CLOSE                        =    1;
constexpr int CARA_IDX_LIB_EXPUNGE                      =    2;
constexpr int CARA_IDX_LIB_EXTFUNC                      =    3;
constexpr int CARA_IDX_PingLocal                        =    4;
constexpr int CARA_IDX_GetTimeOfDay                     =    5;
constexpr int CARA_IDX_SubmitJob                        =    6;
constexpr int CARA_IDX_PAD_7                            =    7;
constexpr int CARA_IDX_SharedAlias1                     =    8;
constexpr int CARA_IDX_SharedAlias2                     =    9;

// V36+ canonical LVO offsets — header constants and
// Phase 9 binary-translator lookup keys, NOT physical
// memory offsets at runtime on RV64. See docs/LVO.md §3.1.
constexpr int _LVOLIB_OPEN                         =    -6;
constexpr int _LVOLIB_CLOSE                        =   -12;
constexpr int _LVOLIB_EXPUNGE                      =   -18;
constexpr int _LVOLIB_EXTFUNC                      =   -24;
constexpr int _LVOPingLocal                        =   -30;
constexpr int _LVOGetTimeOfDay                     =   -36;
constexpr int _LVOSubmitJob                        =   -42;
constexpr int _LVOPAD_7                            =   -48;
constexpr int _LVOSharedAlias1                     =   -54;
constexpr int _LVOSharedAlias2                     =   -60;

#endif // SAMPLE_LVO_H
