// SPDX-License-Identifier: BSD-2-Clause
// AUTOGENERATED by tools/lvo-gen from sample.conf — proto/<lib>.h inline stubs.
// Do not edit; regenerate with `make`. Source of truth:
// tools/lvo-gen/sample.conf and docs/LVO.md.

#ifndef PROTO_SAMPLE_H
#define PROTO_SAMPLE_H

#include <exec/libraries.h>
#include <exec/types.h>

// Forward declaration only. The library's own type
// header (e.g. <sample/samplebase.h>) is what user code must
// include to dereference the base struct's fields.
struct SampleBase;
extern struct SampleBase *SampleBase;

[[gnu::always_inline]]
static inline ULONG PingLocal(ULONG a, ULONG b)
{
    typedef ULONG (*_Cara_Fn)(ULONG, ULONG, struct SampleBase *);
    _Cara_Fn _fn =
        (_Cara_Fn)((void **)SampleBase)[-1 - 4 /* CARA_IDX_PingLocal */];
    return _fn(a, b, SampleBase);
}

[[gnu::always_inline]]
static inline void GetTimeOfDay(ULONG* out)
{
    typedef void (*_Cara_Fn)(ULONG*, struct SampleBase *);
    _Cara_Fn _fn =
        (_Cara_Fn)((void **)SampleBase)[-1 - 5 /* CARA_IDX_GetTimeOfDay */];
    _fn(out, SampleBase);
}

// SubmitJob — server flavour: marshalling deferred (LVO.md §12.2).
[[gnu::error("server-flavour stubs not yet wired (see docs/LVO.md §12.2)")]]
extern ULONG SubmitJob(APTR job, ULONG flags);

[[gnu::always_inline]]
static inline ULONG SharedAlias1(ULONG x)
{
    typedef ULONG (*_Cara_Fn)(ULONG, struct SampleBase *);
    _Cara_Fn _fn =
        (_Cara_Fn)((void **)SampleBase)[-1 - 8 /* CARA_IDX_SharedAlias1 */];
    return _fn(x, SampleBase);
}

[[gnu::always_inline]]
static inline ULONG SharedAlias2(ULONG x)
{
    typedef ULONG (*_Cara_Fn)(ULONG, struct SampleBase *);
    _Cara_Fn _fn =
        (_Cara_Fn)((void **)SampleBase)[-1 - 9 /* CARA_IDX_SharedAlias2 */];
    return _fn(x, SampleBase);
}

#endif // PROTO_SAMPLE_H
