// SPDX-License-Identifier: BSD-2-Clause
// AUTOGENERATED by tools/lvo-gen from sample.conf — <lib>_vec.c — vec table + MakeLibrary tags.
// Do not edit; regenerate with `make`. Source of truth:
// tools/lvo-gen/sample.conf and docs/LVO.md.

#include <cara/makelibrary.h>
#include <cara/types.h>
#include <exec/libraries.h>
#include <utility/tagitem.h>
#include <sample/lvo.h>

struct SampleBase;     // forward; full type lives in the
                // library's hand-written init unit.

// External impl symbols — link-time validation that
// the .conf points at real functions.
extern ULONG Croi_Sample_Open(STRPTR, ULONG, struct SampleBase *);
extern void Croi_Sample_Close(struct SampleBase *);
extern void Croi_Sample_Expunge(struct SampleBase *);
extern void Croi_LvoUnimplemented(struct SampleBase *);
extern ULONG Sample_PingLocal(ULONG, ULONG, struct SampleBase *);
extern void Croi_Sample_GetTimeOfDay(ULONG*, struct SampleBase *);
extern void Croi_LvoUnimplemented(struct SampleBase *);
extern ULONG Croi_Sample_SharedImpl(ULONG, struct SampleBase *);
extern ULONG Croi_Sample_SharedImpl(ULONG, struct SampleBase *);

// Placeholder for server-flavour rows until
// docs/LVO.md §12.2 marshalling lands. Returning
// 0 from a real call here is a bug; the application-
// facing proto/<lib>.h declares these with
// [[gnu::error]] so they fail at link time anyway.
extern void Croi_LvoServerStub(void);

void *sample_lib_vec[] = {
    [CARA_IDX_Open] = (void *)Croi_Sample_Open,
    [CARA_IDX_Close] = (void *)Croi_Sample_Close,
    [CARA_IDX_Expunge] = (void *)Croi_Sample_Expunge,
    [CARA_IDX_ExtFunc] = (void *)Croi_LvoUnimplemented,
    [CARA_IDX_PingLocal] = (void *)Sample_PingLocal,
    [CARA_IDX_GetTimeOfDay] = (void *)Croi_Sample_GetTimeOfDay,
    [CARA_IDX_SubmitJob] = (void *)Croi_LvoServerStub,
    [CARA_IDX_PAD_7] = (void *)Croi_LvoUnimplemented,
    [CARA_IDX_SharedAlias1] = (void *)Croi_Sample_SharedImpl,
    [CARA_IDX_SharedAlias2] = (void *)Croi_Sample_SharedImpl,
};

constexpr usize sample_lib_vec_count =
    sizeof(sample_lib_vec) / sizeof(sample_lib_vec[0]);

// Croi_MakeLibrary parameter tags. The library's hand-written
// init unit overlays MKL_VERSION/REVISION/PRIVATE_SIZE/INIT_FN/
// SERVER_PORT_KOBJ before the call. Zero values here mean
// 'caller must set'; the kernel rejects construction if a
// required tag is still zero (Croi_MakeLibrary semantics).
struct TagItem sample_make_args[] = {
    { MKL_NAME,         (IPTR)"sample.library" },
    { MKL_VEC_TABLE,    (IPTR)sample_lib_vec },
    { MKL_VEC_COUNT,    (IPTR)sample_lib_vec_count },
    { MKL_VERSION,      0 },     // caller-overlay
    { MKL_REVISION,     0 },     // caller-overlay
    { MKL_PRIVATE_SIZE, 0 },     // caller-overlay
    { TAG_END,          0 },
};
