// SPDX-License-Identifier: BSD-2-Clause
//
// Croi C entry. Called from _start.S with:
//   hartid    = booting hart's hartid
//   dtb_phys  = physical address of the device tree blob (SBI convention)
//
// Phase 1 slice 1 brings the SBI console up first, parses the FDT to
// learn where the real UART lives, switches the print backend over to
// the polled NS16550 driver, prints a second hello on the new path, and
// halts. No paging, no scheduler, no IPC yet — those land in following
// slices.

#include "kernel.h"
#include "ns16550.h"
#include "print.h"

#include <cara/alloc.h>
#include <cara/dath.h>
#include <cara/exec_lib.h>
#include <cara/exec_lib_image.h>
#include <cara/fdt.h>
#include <cara/hid.h>
#include <cara/intuition_lib.h>
#include <cara/leargas.h>
#include <cara/log.h>
#include <cara/makelibrary.h>
#include <cara/mm.h>
#include <cara/pci.h>
#include <cara/platform.h>
#include <cara/sched.h>
#include <cara/shared.h>
#include <cara/test.h>
#include <cara/time.h>
#include <cara/trap.h>
#include <cara/types.h>
#include <cara/xhci.h>
#include <exec/libraries.h>
#include <intuition/intuitionbase.h>
#include <utility/tagitem.h>

// Boot-time PCIe inventory. Populated by Croi_Pci_Init from the FDT
// before the test runner so kernel tests (test_pci.c) can assert
// against it. Single-hart Phase 1: no locking needed yet.
struct PciInventory g_pci_inv;
bool g_pci_inited = false;

// Boot-time xHCI controller — probed against the first
// PCI_CLASS_USB_XHCI function found in g_pci_inv. test_xhci asserts
// the reset path completed; the rest of the controller bring-up
// (DCBAA, rings, Run/Stop, port walk, HID) lands in follow-on
// commits per PHASE1_USB.md Tier 1 Epic UB.
struct XhciController g_xhci;
bool g_xhci_probed = false;

// Generated by tools/lvo-gen from tools/lvo-gen/exec.conf at build
// time (see cmake/CaraLvoGen.cmake). The vec table holds 92 entries
// — 4 reserved + the V36+ user-LVO range up to OpenLibrary at -552.
extern void *exec_lib_vec[];
extern const usize exec_lib_vec_count;

// Generated likewise from tools/lvo-gen/intuition.conf. Unlike exec
// (linker-placed at a fixed user VA), intuition.library's base + vec
// table are allocated in the SASOS shared heap at construction time
// (entry.c below), so we only need the vec here.
extern void *intuition_lib_vec[];
extern const usize intuition_lib_vec_count;

// Kernel-image extents materialised into upper-half rodata by the
// linker script's .kernel_extents — see croi.lds. We can't reach the
// low-phys symbols directly from upper-half code (39-bit gap).
extern u64 _kernel_image_phys_start;
extern u64 _kernel_image_phys_end;

[[noreturn]] void croi_entry(u64 hartid, u64 dtb_phys);

struct Ns16550 g_console_uart;
struct PageAllocator g_page_alloc;
struct Heap g_heap;

// Framebuffer + framebuffer-console state. Populated only when the FDT
// exposes a simple-framebuffer node; otherwise left zeroed and the FB
// LogSink is never registered.
static struct DathFramebuffer g_fb;
static struct DathConsole g_fb_console;
static bool g_fb_present = false;

// Leargas LB+LA+LC boot state — initialised when the framebuffer is
// up. The save buffer is a Dath_AllocBitmap-allocated off-screen
// surface sized to the default arrow image. `g_leargas_up` gates
// the post-HID Drain so we don't poke uninitialised state in
// headless boots.
static struct LeargasPointer g_pointer;
static struct DathFramebuffer g_pointer_save;
static struct Screen *g_screen;
static bool g_leargas_up = false;

// Croi runs in the upper-half kernel VA. The boot Sv39 PT mirrors the
// lower 4 GiB into the upper half at L2[256..259], so any physical
// address P is reachable as P + KERNEL_VA_OFFSET. Anything we read from
// hardware-handed-off pointers (DTB, MMIO bases) needs this fixup.
#define KERNEL_VA_OFFSET 0xFFFFFFC000000000ULL

static inline const void *phys_to_virt(u64 phys)
{
    return (const void *)(uptr)(phys + KERNEL_VA_OFFSET);
}

static void console_putc(char c)
{
    ns16550_putc(&g_console_uart, c);
}

[[noreturn]] void croi_entry(u64 hartid, u64 dtb_phys)
{
    Croi_TrapInit();

    Croi_Print("Hello from Croi (SBI), hart=%llu dtb=0x%llx\n", hartid, dtb_phys);

    struct Fdt fdt;
    int rc = Fdt_Open(&fdt, phys_to_virt(dtb_phys));
    if (rc != CARA_EOK) {
        Croi_Print("Fdt_Open failed: %d\n", rc);
        Croi_Halt();
    }

    struct CroiPlatform plat = {};
    rc = Platform_FromFdt(&plat, &fdt);
    if (rc != CARA_EOK) {
        Croi_Print("Platform_FromFdt failed: %d\n", rc);
        Croi_Halt();
    }

    if (plat.console.kind != CROI_UART_NS16550) {
        Croi_Print("no NS16550 console found in FDT\n");
        Croi_Halt();
    }

    Croi_Print("console: base=0x%llx irq=%u shift=%u width=%u clock=%u baud=%u\n",
               plat.console.base, plat.console.irq, plat.console.reg_shift,
               plat.console.reg_io_width, plat.console.clock_hz, plat.console.baud);

    g_console_uart.base = (uptr)phys_to_virt(plat.console.base);
    g_console_uart.shift = plat.console.reg_shift;
    g_console_uart.width = plat.console.reg_io_width ? plat.console.reg_io_width : 1;
    ns16550_init(&g_console_uart, plat.console.clock_hz, plat.console.baud);

    Croi_PrintInstallBackend(console_putc);
    Croi_Print("Hello from Croi (NS16550), hart=%llu\n", hartid);

    // ---- Time first, so subsequent log records have meaningful timestamps.
    if (plat.sstc_present && plat.timebase_hz != 0) {
        Croi_Time_Init(plat.timebase_hz);
    }

    // ---- Leargas L0: input-event ring. Pure storage init; safe to
    //      run unconditionally even when there's no HID to feed it.
    (void)Leargas_Input_Init();

    // LF — install the keyboard router so RAWKEY events from the HID
    // poll reach the focused window's IDCMP port. Harmless before any
    // window exists (the hook drops keys when there's no focus / port);
    // the boot demo window opens before Sched_Init, so it has no port
    // and keys are dropped until a post-scheduler client owns one.
    Leargas_SetKeyRouter(Leargas_IDCMP_RouteKey);
    // LH — install the GADGETUP router so a string Inntin's Return posts
    // IDCMP_GADGETUP to its window's port.
    Leargas_SetGadgetRouter(Leargas_IDCMP_PostGadgetUp);

    // ---- Physical memory map ----
    u64 kphys_start = _kernel_image_phys_start;
    u64 kphys_end = _kernel_image_phys_end;
    u64 dtb_start = dtb_phys;
    u64 dtb_end = dtb_phys + fdt.totalsize;

    struct PhysMap pm;
    rc = Mm_PhysMapFromFdt(&pm, &fdt, kphys_start, kphys_end, dtb_start, dtb_end);
    if (rc != CARA_EOK) {
        Croi_Print("Mm_PhysMapFromFdt failed: %d\n", rc);
        Croi_Halt();
    }

    // ---- Page allocator ----
    rc = Page_Init(&g_page_alloc, &pm);
    if (rc != CARA_EOK) {
        Croi_Print("Page_Init failed: %d\n", rc);
        Croi_Halt();
    }

    // ---- Kernel heap ----
    rc = Heap_Init(&g_heap, &g_page_alloc);
    if (rc != CARA_EOK) {
        Croi_Print("Heap_Init failed: %d\n", rc);
        Croi_Halt();
    }
    Heap_SetActive(&g_heap);

    // ---- Structured logging on top of the heap ----
    if (Log_Init() != CARA_EOK) {
        Croi_Print("Log_Init failed\n");
        Croi_Halt();
    }
    struct LogSink uart_sink = {
        .emit = Log_Sink_NS16550_Emit,
        .ctx = &g_console_uart,
        .ansi_capable = true,
        .min_level = (u8)LOG_LV_TRACE,
    };
    if (Log_RegisterSink(&uart_sink) != CARA_EOK) {
        Croi_Print("Log_RegisterSink failed\n");
        Croi_Halt();
    }

    // ---- SASOS shared heap. Maps the lower-half RW+U shared window
    //      (ARCHITECTURE §4.3) and registers it with the allocator so
    //      AllocMem / library bodies can return U-mode-dereferenceable
    //      pointers. Installed into the boot PT here; spawn paths install
    //      it into each task PT.
    if (Croi_Shared_Init(&g_page_alloc) != CARA_EOK) {
        LOG_FATAL("entry", "Croi_Shared_Init failed");
        Croi_Halt();
    }

    // From here forward, prefer LOG_* over Croi_Print so output is
    // captured in the ring and routed through every active sink.
    LOG_INFO("boot", "CaraOS Croi up at upper-half VAs (hart=%llu)", hartid);
    LOG_INFO("mem ", "kernel image: 0x%llx..0x%llx (%llu KiB)", kphys_start, kphys_end,
             (kphys_end - kphys_start) / 1024);
    LOG_INFO("mem ", "dtb:          0x%llx..0x%llx (%llu bytes)", dtb_start, dtb_end,
             dtb_end - dtb_start);
    LOG_INFO("mem ", "phys: %llu MiB across %u banks; usable %llu MiB across %u runs",
             pm.total_bytes / (1024 * 1024), pm.n_banks, pm.usable_bytes / (1024 * 1024),
             pm.n_usable);
    LOG_INFO("mem ", "page allocator: %llu pages free", g_page_alloc.free_pages);
    LOG_INFO("mem ", "heap: %u classes, ready", CARA_HEAP_NUM_CLASSES);
    LOG_INFO("uart", "NS16550 base=0x%llx irq=%u shift=%u width=%u", plat.console.base,
             plat.console.irq, plat.console.reg_shift, plat.console.reg_io_width);
    LOG_INFO("time", "timebase=%llu Hz, sstc=%s", plat.timebase_hz,
             plat.sstc_present ? "present" : "absent");

    for (u32 i = 0; i < pm.n_usable; i++) {
        LOG_DEBUG("mem ", "usable[%u]: 0x%llx..0x%llx (%llu KiB)", i, pm.usable[i].base,
                  pm.usable[i].base + pm.usable[i].size, pm.usable[i].size / 1024);
    }
    // ---- Probe simple-framebuffer (optional). On QEMU virt without
    //      `-device ramfb` there's no FDT node so we just log and skip;
    //      on real boards U-Boot leaves a node here when HDMI's up.
    {
        struct DathFbDescriptor fbdesc;
        int frc = Dath_Framebuffer_FromFdt(&fbdesc, &fdt);
        if (frc == CARA_EOK) {
            LOG_INFO("dath", "simple-framebuffer %ux%u stride=%u fmt=%u base=0x%llx", fbdesc.width,
                     fbdesc.height, fbdesc.stride, (u32)fbdesc.format, fbdesc.phys_base);
            if (Dath_Framebuffer_Init(&g_fb, Mm_PhysToVirt(fbdesc.phys_base), fbdesc.width,
                                      fbdesc.height, fbdesc.stride, fbdesc.format) == CARA_EOK) {
                // Boot banner: dark-blue background, light-blue 1-pixel
                // border, white "CaraOS" wordmark + subtitle, then a
                // red/green/blue swatch row below so the format encoding
                // is visible at a glance.
                DathColor bg = Dath_RGB(0x10, 0x20, 0x40);
                DathColor accent = Dath_RGB(0x40, 0x80, 0xFF);
                DathColor white = Dath_RGB(0xFF, 0xFF, 0xFF);
                DathColor red = Dath_RGB(0xFF, 0x40, 0x40);
                DathColor green = Dath_RGB(0x40, 0xFF, 0x40);
                DathColor blue = Dath_RGB(0x40, 0x80, 0xFF);
                if (g_fb.format == DATH_FMT_RGB565) {
                    bg = Dath_RGB565(0x10, 0x20, 0x40);
                    accent = Dath_RGB565(0x40, 0x80, 0xFF);
                    white = Dath_RGB565(0xFF, 0xFF, 0xFF);
                    red = Dath_RGB565(0xFF, 0x40, 0x40);
                    green = Dath_RGB565(0x40, 0xFF, 0x40);
                    blue = Dath_RGB565(0x40, 0x80, 0xFF);
                }

                Dath_Clear(&g_fb, bg);
                Dath_DrawRect(&g_fb, 0, 0, (i32)g_fb.width, (i32)g_fb.height, accent);
                Dath_DrawString(&g_fb, &dath_font_8x8, 16, 16, "CaraOS", white, bg);
                Dath_DrawString(&g_fb, &dath_font_8x8, 16, 28, "RISC-V kernel boot", accent, bg);
                Dath_FillRect(&g_fb, 16, 48, 32, 12, red);
                Dath_FillRect(&g_fb, 56, 48, 32, 12, green);
                Dath_FillRect(&g_fb, 96, 48, 32, 12, blue);

                Dath_Console_Init(&g_fb_console, &g_fb, &dath_font_8x8, white, bg);
                g_fb_console.cur_row = 9;
                g_fb_console.cur_col = 0;
                g_fb_present = true;
                // Phase 1 deliberately does NOT register the framebuffer
                // as a LogSink: once Leargas LB takes over the screen
                // (next block), windows + pointer would be overpainted
                // by every subsequent LOG_INFO line. The DathConsole is
                // kept around so Phase 3 can route logs to a dedicated
                // "Console" window via the same emit fn. UART log keeps
                // everything for debugging.

                // ---- Leargas LB + LA boot init. Ride the existing
                //      banner colours so OpenScreen's Dath_Clear
                //      doesn't visually flash. The pointer renders
                //      on top; LC's Drain (after HID poll) drives
                //      it from IECLASS_RAWMOUSE events on the L0
                //      ring.
                if (Dath_AllocBitmap(&g_pointer_save, leargas_pointer_arrow.width,
                                     leargas_pointer_arrow.height, g_fb.format) == CARA_EOK) {
                    g_screen = Leargas_OpenScreen(&g_fb, "Workbench", bg);
                    if (g_screen) {
                        // LD: open a sample window centered on the
                        // screen so the framebuffer shows boot
                        // chrome (border + title bar + close
                        // gadget). Order matters — Pointer_Init
                        // must follow OpenWindow so the pointer's
                        // save buffer captures the with-window
                        // pixels at center; otherwise the first
                        // Pointer_Move would restore stale pre-
                        // window pixels and corrupt the title bar.
                        char wb_title[] = "Croi";
                        i32 win_w = (i32)g_fb.width - 200;
                        i32 win_h = (i32)g_fb.height - 120;
                        if (win_w < 120) {
                            win_w = 120;
                        }
                        if (win_h < 60) {
                            win_h = 60;
                        }
                        struct NewWindow nw = {
                            .LeftEdge = (WORD)(((i32)g_fb.width - win_w) / 2),
                            .TopEdge = (WORD)(((i32)g_fb.height - win_h) / 2),
                            .Width = (WORD)win_w,
                            .Height = (WORD)win_h,
                            .DetailPen = 0,
                            .BlockPen = 1,
                            .IDCMPFlags = IDCMP_CLOSEWINDOW | IDCMP_RAWKEY | IDCMP_MOUSEBUTTONS |
                                          IDCMP_MOUSEMOVE,
                            .Flags = WFLG_DRAGBAR | WFLG_DEPTHGADGET | WFLG_CLOSEGADGET |
                                     WFLG_ACTIVATE | WFLG_SMART_REFRESH,
                            .Title = (UBYTE *)wb_title,
                            .Screen = g_screen,
                            .MinWidth = 120,
                            .MinHeight = 60,
                            .MaxWidth = (UWORD)g_fb.width,
                            .MaxHeight = (UWORD)g_fb.height,
                            .Type = WBENCHSCREEN,
                        };
                        struct Window *win = Leargas_OpenWindow(&nw);
                        if (win) {
                            LOG_INFO("larg", "window '%s' at (%d,%d) %dx%d", wb_title,
                                     (int)win->LeftEdge, (int)win->TopEdge, (int)win->Width,
                                     (int)win->Height);
                            // LE — WFLG_ACTIVATE focused the window at
                            // open; a left-click (via the HID poll →
                            // Leargas_Input_Drain) re-focuses whichever
                            // window the pointer is over.
                            LOG_INFO("larg", "active window: %s",
                                     Leargas_ActiveWindow() == win ? wb_title : "(none)");
                        } else {
                            LOG_WARN("larg", "OpenWindow failed");
                        }

                        // Pointer fg=white (body), bg=black (outline) so
                        // both pixel kinds contrast against the dark-blue
                        // screen pen0. Reusing screen bg as the outline
                        // colour makes the outline disappear against
                        // similarly-coloured backgrounds.
                        DathColor ptr_outline = (g_fb.format == DATH_FMT_RGB565)
                                                    ? Dath_RGB565(0, 0, 0)
                                                    : Dath_RGB(0, 0, 0);
                        if (Leargas_Pointer_Init(&g_pointer, &g_fb, &g_pointer_save,
                                                 &leargas_pointer_arrow, white, ptr_outline,
                                                 (i32)g_fb.width / 2,
                                                 (i32)g_fb.height / 2) == CARA_EOK) {
                            g_leargas_up = true;
                            LOG_INFO("larg", "screen %ux%u + pointer at (%d, %d)",
                                     (unsigned)g_fb.width, (unsigned)g_fb.height, (int)g_pointer.x,
                                     (int)g_pointer.y);
                        } else {
                            LOG_WARN("larg", "Pointer_Init failed");
                            if (win) {
                                Leargas_CloseWindow(win);
                            }
                            Leargas_CloseScreen(g_screen);
                            g_screen = nullptr;
                        }
                    } else {
                        LOG_WARN("larg", "OpenScreen failed");
                    }
                } else {
                    LOG_WARN("larg", "AllocBitmap for pointer save failed");
                }
            }
        } else if (frc == CARA_ENOTFOUND) {
            LOG_INFO("dath", "no simple-framebuffer in FDT; headless boot");
        } else {
            LOG_WARN("dath", "FromFdt failed: %d", frc);
        }
    }

    // ---- PCIe enumeration. Discovers the host bridge from the FDT
    //      and walks the bus; subsequent drivers (xHCI, NVMe, …)
    //      pick functions out of g_pci_inv via Croi_Pci_FindByClass.
    {
        int prc = Croi_Pci_Init(&g_pci_inv, &fdt);
        if (prc == CARA_EOK) {
            g_pci_inited = true;
        } else if (prc == CARA_ENOTFOUND) {
            LOG_INFO("pci ", "no pci-host-ecam-generic node; PCIe disabled");
        } else {
            LOG_WARN("pci ", "Croi_Pci_Init failed: %d", prc);
        }
    }

    // ---- xHCI host controller. First xHCI function gets probed and
    //      reset; later milestones bring up the Command/Event rings
    //      and walk PORTSC for connected devices.
    if (g_pci_inited) {
        u32 cursor = 0;
        const struct PciFunction *xfn = Croi_Pci_FindByClass(&g_pci_inv, PCI_CLASS_USB_XHCI_BASE,
                                                             PCI_CLASS_USB_XHCI_SUB,
                                                             PCI_CLASS_USB_XHCI_PROGIF, &cursor);
        if (xfn) {
            // Croi_Pci_FindByClass returned a const pointer into the
            // inventory; recover the index for Croi_Xhci_Probe (which
            // mutates the function record's bar[]).
            u32 fidx = (u32)(xfn - g_pci_inv.func);
            int xrc = Croi_Xhci_Probe(&g_xhci, &g_pci_inv, fidx);
            if (xrc == CARA_EOK) {
                g_xhci_probed = true;
                int src = Croi_Xhci_Setup(&g_xhci);
                if (src != CARA_EOK) {
                    LOG_WARN("xhci", "setup failed: %d", src);
                } else {
                    int prc = Croi_Xhci_PortsWalk(&g_xhci);
                    if (prc != CARA_EOK) {
                        LOG_WARN("xhci", "PortsWalk failed: %d", prc);
                    } else {
                        int arc = Croi_Xhci_AddressConnectedDevices(&g_xhci);
                        if (arc != CARA_EOK) {
                            LOG_WARN("xhci", "AddressConnectedDevices failed: %d", arc);
                        } else {
                            int drc = Croi_Xhci_ReadDescriptors(&g_xhci);
                            if (drc != CARA_EOK) {
                                LOG_WARN("xhci", "ReadDescriptors failed: %d", drc);
                            } else {
                                int crc = Croi_Xhci_ReadConfigurations(&g_xhci);
                                if (crc != CARA_EOK) {
                                    LOG_WARN("xhci", "ReadConfigurations failed: %d", crc);
                                } else {
                                    int sc = Croi_Xhci_ConfigureSlots(&g_xhci);
                                    if (sc != CARA_EOK) {
                                        LOG_WARN("xhci", "ConfigureSlots failed: %d", sc);
                                    } else {
                                        int dr = Croi_Xhci_DispatchInterfaces(&g_xhci);
                                        if (dr != CARA_EOK) {
                                            LOG_WARN("xhci", "DispatchInterfaces failed: %d", dr);
                                        } else {
                                            int er = Croi_Xhci_ConfigureHidInterrupts(&g_xhci);
                                            if (er != CARA_EOK) {
                                                LOG_WARN("xhci",
                                                         "ConfigureHidInterrupts failed: %d", er);
                                            } else {
                                                int hp = Croi_Xhci_HidSetBootProtocols(&g_xhci);
                                                if (hp != CARA_EOK) {
                                                    LOG_WARN("xhci",
                                                             "HidSetBootProtocols failed: %d", hp);
                                                } else {
                                                    // Boot-time bring-up poll of each
                                                    // HID interrupt-IN endpoint. With no
                                                    // input injection in the smoke harness
                                                    // these all timeout (EAGAIN) — we
                                                    // just log that the substrate works.
                                                    for (u32 sid = 1; sid <= CARA_XHCI_MAX_SLOTS;
                                                         sid++) {
                                                        if (!g_xhci.slots[sid].in_use)
                                                            continue;
                                                        for (u32 j = 0;
                                                             j < g_xhci.slots[sid].n_interfaces;
                                                             j++) {
                                                            const auto iface =
                                                                &g_xhci.slots[sid].interfaces[j];
                                                            if (iface->dispatch !=
                                                                    XHCI_HID_KEYBOARD &&
                                                                iface->dispatch != XHCI_HID_MOUSE) {
                                                                continue;
                                                            }
                                                            u32 got = 0;
                                                            int rr = Croi_Xhci_HidIntReadOnce(
                                                                &g_xhci, (u8)sid, j, 300000u, &got);
                                                            if (rr == CARA_EOK) {
                                                                LOG_INFO("xhci",
                                                                         "slot=%u iface[%u] %s "
                                                                         "int-IN report (%u bytes)",
                                                                         (unsigned)sid, (unsigned)j,
                                                                         iface->dispatch ==
                                                                                 XHCI_HID_KEYBOARD
                                                                             ? "kbd"
                                                                             : "mouse",
                                                                         (unsigned)got);
                                                                // Decode it through the cara_hid
                                                                // boot decoders so we exercise
                                                                // HA.2/HA.3 end-to-end against real
                                                                // bytes.
                                                                if (iface->dispatch ==
                                                                    XHCI_HID_KEYBOARD) {
                                                                    struct CaraHidKeyboardReport kr;
                                                                    if (Croi_Hid_DecodeKeyboardBoot(
                                                                            (const u8 *)
                                                                                iface->last_report,
                                                                            iface->last_report_bytes,
                                                                            &kr) == CARA_EOK) {
                                                                        u8 raw0 =
                                                                            Croi_Hid_UsageToRawKey(
                                                                                kr.keys[0]);
                                                                        LOG_INFO(
                                                                            "xhci",
                                                                            "  kbd: mods=0x%x "
                                                                            "ie_qual=0x%x "
                                                                            "usage[0]=0x%x "
                                                                            "rawkey=0x%x",
                                                                            (unsigned)kr.modifiers,
                                                                            (unsigned)
                                                                                kr.ie_qualifier,
                                                                            (unsigned)kr.keys[0],
                                                                            (unsigned)raw0);
                                                                        // Phase 1 L0 seam: post
                                                                        // the first pressed key
                                                                        // through the input ring.
                                                                        // Full N-key rollover +
                                                                        // up-stroke tracking lands
                                                                        // with the HID Gleas
                                                                        // (HB.* / Phase 3).
                                                                        if (raw0 !=
                                                                            CARA_RAWKEY_NONE) {
                                                                            struct LeargasInputEvent ev = {
                                                                                .ie_class =
                                                                                    IECLASS_RAWKEY,
                                                                                .ie_code = raw0,
                                                                                .ie_qualifier =
                                                                                    kr.ie_qualifier,
                                                                                .ie_ts_ns =
                                                                                    Croi_Time_Now(),
                                                                            };
                                                                            (void)Leargas_Input_Post(
                                                                                &ev);
                                                                        }
                                                                    }
                                                                } else {
                                                                    struct CaraHidMouseReport mr;
                                                                    if (Croi_Hid_DecodeMouseBoot(
                                                                            (const u8 *)
                                                                                iface->last_report,
                                                                            iface->last_report_bytes,
                                                                            &mr) == CARA_EOK) {
                                                                        LOG_INFO(
                                                                            "xhci",
                                                                            "  mouse: btns=0x%x "
                                                                            "dx=%d dy=%d wheel=%d "
                                                                            "ie_qual=0x%x",
                                                                            (unsigned)mr.buttons,
                                                                            (int)mr.dx, (int)mr.dy,
                                                                            (int)mr.wheel,
                                                                            (unsigned)
                                                                                mr.ie_qualifier);
                                                                        struct LeargasInputEvent
                                                                            ev = {
                                                                                .ie_class =
                                                                                    IECLASS_RAWMOUSE,
                                                                                .ie_code =
                                                                                    IECODE_NOBUTTON,
                                                                                .ie_qualifier =
                                                                                    mr.ie_qualifier,
                                                                                .ie_dx = mr.dx,
                                                                                .ie_dy = mr.dy,
                                                                                .ie_ts_ns =
                                                                                    Croi_Time_Now(),
                                                                            };
                                                                        (void)Leargas_Input_Post(
                                                                            &ev);
                                                                    }
                                                                }
                                                            } else {
                                                                LOG_INFO("xhci",
                                                                         "slot=%u iface[%u] %s "
                                                                         "int-IN idle (no input)",
                                                                         (unsigned)sid, (unsigned)j,
                                                                         iface->dispatch ==
                                                                                 XHCI_HID_KEYBOARD
                                                                             ? "kbd"
                                                                             : "mouse");
                                                            }
                                                        }
                                                    }
                                                    // LC: drive the pointer from the L0 ring.
                                                    // Without an active framebuffer the
                                                    // pointer state isn't initialised, so we
                                                    // skip Drain — events stay queued and
                                                    // are dropped at next reboot. With one
                                                    // up, RAWMOUSE events accumulate onto
                                                    // the pointer and clamp against the
                                                    // active screen extent; RAWKEY events
                                                    // are consumed but dropped (LF will own
                                                    // them once it lands).
                                                    if (g_leargas_up) {
                                                        u32 drained =
                                                            Leargas_Input_Drain(&g_pointer);
                                                        LOG_INFO("larg",
                                                                 "drained %u event(s); "
                                                                 "pointer at (%d, %d)",
                                                                 (unsigned)drained,
                                                                 (int)g_pointer.x,
                                                                 (int)g_pointer.y);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                LOG_WARN("xhci", "probe failed: %d", xrc);
            }
        } else {
            LOG_INFO("xhci", "no xHCI controller in PCI inventory");
        }
    }

    // ---- Bring up the cooperative scheduler before running tests so
    //      the sched_smoke test can spawn workers and yield.
    Sched_Init();

    // ---- Construct exec.library.
    //      The library image lives in the .exec_lib section
    //      (croi.lds, VMA = 0x4000_0000). We hand Croi_MakeLibrary
    //      the kernel-side direct-map view of that region (since
    //      the kernel's PT doesn't map the user-VA), the generated
    //      vec table, and the V36+ version/revision/private-size.
    //      The library registers itself in the exec.library
    //      LibList; user-mode code reaches it via OpenLibrary
    //      starting in Phase D.
    {
        // First install the .exec_lib mapping in the boot PT so
        // kmain can read+write the user-VA 0x4000_0000 region.
        // (Croi_ExecLib_InstallMapping has already been wired into
        // every user task's PT in the spawn paths, but kmain itself
        // runs with the boot PT until it spawns user tasks.)
        if (Croi_ExecLib_InstallInBootPT() != CARA_EOK) {
            LOG_FATAL("entry", "InstallInBootPT(.exec_lib) failed");
            Croi_Halt();
        }

        // exec.library is linker-placed at user-VA 0x4000_0800.
        // Both kernel and user mode see this VA after the boot-PT
        // install above plus per-task PT install in spawn paths.
        struct Library *user_base = (struct Library *)CARA_EXEC_LIB_USER_BASE;
        struct TagItem mklib_tags[] = {
            { MKL_NAME, (IPTR) "exec.library" },
            { MKL_BASE, (IPTR)user_base },
            { MKL_VEC_TABLE, (IPTR)exec_lib_vec },
            { MKL_VEC_COUNT, (IPTR)exec_lib_vec_count },
            { MKL_VERSION, 36 },
            { MKL_REVISION, 0 },
            { MKL_PRIVATE_SIZE, (IPTR)Croi_ExecLib_PrivateSize() },
            { TAG_END, 0 },
        };
        struct Library *base = Croi_MakeLibrary(mklib_tags);
        if (!base) {
            LOG_FATAL("entry", "Croi_MakeLibrary(exec.library) failed");
            Croi_Halt();
        }
    }

    // ---- Construct intuition.library (I3).
    //      Unlike exec.library (linker-placed at the fixed user VA
    //      0x4000_0800), intuition.library's base + negative-side vec
    //      table live in the SASOS shared heap (ARCHITECTURE §4.3,
    //      0x1_0000_0000). Because sstatus.SUM=1, that lower-half VA is
    //      writable from S-mode and readable from U-mode through the
    //      SAME pointer — so MKL_BASE and the kernel-write view coincide
    //      (no separate MKL_BASE_KERNEL_WRITE as exec needs). The
    //      trampolines its vec entries point at still live in the shared
    //      0x4000_0000 RX region (.lib_text.intuition). User code
    //      discovers the base at runtime via OpenLibrary, not a fixed VA.
    {
        usize priv_size = sizeof(struct IntuitionBase) - sizeof(struct Library);
        usize neg_size = sizeof(void *) * intuition_lib_vec_count;
        usize block_size = neg_size + sizeof(struct Library) + priv_size;

        u8 *block = (u8 *)Croi_AllocShared(block_size);
        if (!block) {
            LOG_FATAL("entry", "AllocShared(intuition.library, %llu bytes) failed",
                      (u64)block_size);
            Croi_Halt();
        }
        struct Library *ibase = (struct Library *)(block + neg_size);

        struct TagItem mklib_tags[] = {
            { MKL_NAME, (IPTR) "intuition.library" },
            { MKL_BASE, (IPTR)ibase },
            { MKL_VEC_TABLE, (IPTR)intuition_lib_vec },
            { MKL_VEC_COUNT, (IPTR)intuition_lib_vec_count },
            { MKL_VERSION, 36 },
            { MKL_REVISION, 0 },
            { MKL_PRIVATE_SIZE, (IPTR)priv_size },
            { TAG_END, 0 },
        };
        struct Library *base = Croi_MakeLibrary(mklib_tags);
        if (!base) {
            LOG_FATAL("entry", "Croi_MakeLibrary(intuition.library) failed");
            Croi_Halt();
        }
    }

    // ---- Run the in-kernel test suite. ----
    Test_RunAll();

    Croi_Halt();
}
