// SPDX-License-Identifier: BSD-2-Clause
//
// Croi C entry. Called from _start.S with:
//   hartid    = booting hart's hartid
//   dtb_phys  = physical address of the device tree blob (SBI convention)
//
// Phase 1 slice 1 brings the SBI console up first, parses the FDT to
// learn where the real UART lives, switches the print backend over to
// the polled NS16550 driver, prints a second hello on the new path, and
// halts. No paging, no scheduler, no IPC yet — those land in following
// slices.

#include "kernel.h"
#include "ns16550.h"
#include "print.h"

#include <cara/alloc.h>
#include <cara/dath.h>
#include <cara/exec_lib.h>
#include <cara/exec_lib_image.h>
#include <cara/fdt.h>
#include <cara/log.h>
#include <cara/makelibrary.h>
#include <cara/mm.h>
#include <cara/pci.h>
#include <cara/platform.h>
#include <cara/xhci.h>
#include <cara/sched.h>
#include <cara/test.h>
#include <cara/time.h>
#include <cara/trap.h>
#include <cara/types.h>
#include <exec/libraries.h>
#include <utility/tagitem.h>

// Boot-time PCIe inventory. Populated by Croi_Pci_Init from the FDT
// before the test runner so kernel tests (test_pci.c) can assert
// against it. Single-hart Phase 1: no locking needed yet.
struct PciInventory g_pci_inv;
bool                g_pci_inited = false;

// Boot-time xHCI controller — probed against the first
// PCI_CLASS_USB_XHCI function found in g_pci_inv. test_xhci asserts
// the reset path completed; the rest of the controller bring-up
// (DCBAA, rings, Run/Stop, port walk, HID) lands in follow-on
// commits per PHASE1_USB.md Tier 1 Epic UB.
struct XhciController g_xhci;
bool                  g_xhci_probed = false;

// Generated by tools/lvo-gen from tools/lvo-gen/exec.conf at build
// time (see cmake/CaraLvoGen.cmake). The vec table holds 92 entries
// — 4 reserved + the V36+ user-LVO range up to OpenLibrary at -552.
extern void       *exec_lib_vec[];
extern const usize exec_lib_vec_count;

// Kernel-image extents materialised into upper-half rodata by the
// linker script's .kernel_extents — see croi.lds. We can't reach the
// low-phys symbols directly from upper-half code (39-bit gap).
extern u64 _kernel_image_phys_start;
extern u64 _kernel_image_phys_end;

[[noreturn]] void croi_entry(u64 hartid, u64 dtb_phys);

struct Ns16550 g_console_uart;
struct PageAllocator g_page_alloc;
struct Heap g_heap;

// Framebuffer + framebuffer-console state. Populated only when the FDT
// exposes a simple-framebuffer node; otherwise left zeroed and the FB
// LogSink is never registered.
static struct DathFramebuffer g_fb;
static struct DathConsole     g_fb_console;
static bool                   g_fb_present = false;

// Croi runs in the upper-half kernel VA. The boot Sv39 PT mirrors the
// lower 4 GiB into the upper half at L2[256..259], so any physical
// address P is reachable as P + KERNEL_VA_OFFSET. Anything we read from
// hardware-handed-off pointers (DTB, MMIO bases) needs this fixup.
#define KERNEL_VA_OFFSET 0xFFFFFFC000000000ULL

static inline const void *phys_to_virt(u64 phys)
{
    return (const void *)(uptr)(phys + KERNEL_VA_OFFSET);
}

static void console_putc(char c)
{
    ns16550_putc(&g_console_uart, c);
}

[[noreturn]] void croi_entry(u64 hartid, u64 dtb_phys)
{
    Croi_TrapInit();

    Croi_Print("Hello from Croi (SBI), hart=%llu dtb=0x%llx\n", hartid,
               dtb_phys);

    struct Fdt fdt;
    int rc = Fdt_Open(&fdt, phys_to_virt(dtb_phys));
    if (rc != CARA_EOK) {
        Croi_Print("Fdt_Open failed: %d\n", rc);
        Croi_Halt();
    }

    struct CroiPlatform plat = {};
    rc = Platform_FromFdt(&plat, &fdt);
    if (rc != CARA_EOK) {
        Croi_Print("Platform_FromFdt failed: %d\n", rc);
        Croi_Halt();
    }

    if (plat.console.kind != CROI_UART_NS16550) {
        Croi_Print("no NS16550 console found in FDT\n");
        Croi_Halt();
    }

    Croi_Print("console: base=0x%llx irq=%u shift=%u width=%u clock=%u baud=%u\n",
               plat.console.base, plat.console.irq, plat.console.reg_shift,
               plat.console.reg_io_width, plat.console.clock_hz,
               plat.console.baud);

    g_console_uart.base = (uptr)phys_to_virt(plat.console.base);
    g_console_uart.shift = plat.console.reg_shift;
    g_console_uart.width = plat.console.reg_io_width ? plat.console.reg_io_width : 1;
    ns16550_init(&g_console_uart, plat.console.clock_hz, plat.console.baud);

    Croi_PrintInstallBackend(console_putc);
    Croi_Print("Hello from Croi (NS16550), hart=%llu\n", hartid);

    // ---- Time first, so subsequent log records have meaningful timestamps.
    if (plat.sstc_present && plat.timebase_hz != 0) {
        Croi_Time_Init(plat.timebase_hz);
    }

    // ---- Physical memory map ----
    u64 kphys_start = _kernel_image_phys_start;
    u64 kphys_end = _kernel_image_phys_end;
    u64 dtb_start = dtb_phys;
    u64 dtb_end = dtb_phys + fdt.totalsize;

    struct PhysMap pm;
    rc = Mm_PhysMapFromFdt(&pm, &fdt, kphys_start, kphys_end, dtb_start, dtb_end);
    if (rc != CARA_EOK) {
        Croi_Print("Mm_PhysMapFromFdt failed: %d\n", rc);
        Croi_Halt();
    }

    // ---- Page allocator ----
    rc = Page_Init(&g_page_alloc, &pm);
    if (rc != CARA_EOK) {
        Croi_Print("Page_Init failed: %d\n", rc);
        Croi_Halt();
    }

    // ---- Kernel heap ----
    rc = Heap_Init(&g_heap, &g_page_alloc);
    if (rc != CARA_EOK) {
        Croi_Print("Heap_Init failed: %d\n", rc);
        Croi_Halt();
    }
    Heap_SetActive(&g_heap);

    // ---- Structured logging on top of the heap ----
    if (Log_Init() != CARA_EOK) {
        Croi_Print("Log_Init failed\n");
        Croi_Halt();
    }
    struct LogSink uart_sink = {
        .emit = Log_Sink_NS16550_Emit,
        .ctx = &g_console_uart,
        .ansi_capable = true,
        .min_level = (u8)LOG_LV_TRACE,
    };
    if (Log_RegisterSink(&uart_sink) != CARA_EOK) {
        Croi_Print("Log_RegisterSink failed\n");
        Croi_Halt();
    }

    // From here forward, prefer LOG_* over Croi_Print so output is
    // captured in the ring and routed through every active sink.
    LOG_INFO("boot", "CaraOS Croi up at upper-half VAs (hart=%llu)", hartid);
    LOG_INFO("mem ", "kernel image: 0x%llx..0x%llx (%llu KiB)", kphys_start,
             kphys_end, (kphys_end - kphys_start) / 1024);
    LOG_INFO("mem ", "dtb:          0x%llx..0x%llx (%llu bytes)", dtb_start,
             dtb_end, dtb_end - dtb_start);
    LOG_INFO("mem ", "phys: %llu MiB across %u banks; usable %llu MiB across %u runs",
             pm.total_bytes / (1024 * 1024), pm.n_banks,
             pm.usable_bytes / (1024 * 1024), pm.n_usable);
    LOG_INFO("mem ", "page allocator: %llu pages free", g_page_alloc.free_pages);
    LOG_INFO("mem ", "heap: %u classes, ready", CARA_HEAP_NUM_CLASSES);
    LOG_INFO("uart", "NS16550 base=0x%llx irq=%u shift=%u width=%u",
             plat.console.base, plat.console.irq, plat.console.reg_shift,
             plat.console.reg_io_width);
    LOG_INFO("time", "timebase=%llu Hz, sstc=%s", plat.timebase_hz,
             plat.sstc_present ? "present" : "absent");

    for (u32 i = 0; i < pm.n_usable; i++) {
        LOG_DEBUG("mem ", "usable[%u]: 0x%llx..0x%llx (%llu KiB)", i,
                  pm.usable[i].base, pm.usable[i].base + pm.usable[i].size,
                  pm.usable[i].size / 1024);
    }
    // ---- Probe simple-framebuffer (optional). On QEMU virt without
    //      `-device ramfb` there's no FDT node so we just log and skip;
    //      on real boards U-Boot leaves a node here when HDMI's up.
    {
        struct DathFbDescriptor fbdesc;
        int frc = Dath_Framebuffer_FromFdt(&fbdesc, &fdt);
        if (frc == CARA_EOK) {
            LOG_INFO("dath", "simple-framebuffer %ux%u stride=%u fmt=%u base=0x%llx",
                     fbdesc.width, fbdesc.height, fbdesc.stride,
                     (u32)fbdesc.format, fbdesc.phys_base);
            if (Dath_Framebuffer_Init(&g_fb, Mm_PhysToVirt(fbdesc.phys_base),
                                      fbdesc.width, fbdesc.height,
                                      fbdesc.stride, fbdesc.format)
                == CARA_EOK) {
                // Boot banner: dark-blue background, light-blue 1-pixel
                // border, white "CaraOS" wordmark + subtitle, then a
                // red/green/blue swatch row below so the format encoding
                // is visible at a glance.
                DathColor bg     = Dath_RGB(0x10, 0x20, 0x40);
                DathColor accent = Dath_RGB(0x40, 0x80, 0xFF);
                DathColor white  = Dath_RGB(0xFF, 0xFF, 0xFF);
                DathColor red    = Dath_RGB(0xFF, 0x40, 0x40);
                DathColor green  = Dath_RGB(0x40, 0xFF, 0x40);
                DathColor blue   = Dath_RGB(0x40, 0x80, 0xFF);
                if (g_fb.format == DATH_FMT_RGB565) {
                    bg     = Dath_RGB565(0x10, 0x20, 0x40);
                    accent = Dath_RGB565(0x40, 0x80, 0xFF);
                    white  = Dath_RGB565(0xFF, 0xFF, 0xFF);
                    red    = Dath_RGB565(0xFF, 0x40, 0x40);
                    green  = Dath_RGB565(0x40, 0xFF, 0x40);
                    blue   = Dath_RGB565(0x40, 0x80, 0xFF);
                }

                Dath_Clear(&g_fb, bg);
                Dath_DrawRect(&g_fb, 0, 0, (i32)g_fb.width, (i32)g_fb.height,
                              accent);
                Dath_DrawString(&g_fb, &dath_font_8x8, 16, 16,
                                "CaraOS", white, bg);
                Dath_DrawString(&g_fb, &dath_font_8x8, 16, 28,
                                "RISC-V kernel boot", accent, bg);
                Dath_FillRect(&g_fb, 16,  48, 32, 12, red);
                Dath_FillRect(&g_fb, 56,  48, 32, 12, green);
                Dath_FillRect(&g_fb, 96,  48, 32, 12, blue);

                Dath_Console_Init(&g_fb_console, &g_fb, &dath_font_8x8,
                                  white, bg);
                // Reserve the top of the screen for the banner — start
                // the log sink at row 9 (px 72 with the 8x8 font).
                g_fb_console.cur_row = 9;
                g_fb_console.cur_col = 0;
                struct LogSink fb_sink = {
                    .emit = Log_Sink_DathConsole_Emit,
                    .ctx = &g_fb_console,
                    .ansi_capable = false,
                    .min_level = (u8)LOG_LV_INFO,
                };
                if (Log_RegisterSink(&fb_sink) == CARA_EOK) {
                    g_fb_present = true;
                    LOG_INFO("dath", "framebuffer console registered");
                }
            }
        } else if (frc == CARA_ENOTFOUND) {
            LOG_INFO("dath", "no simple-framebuffer in FDT; headless boot");
        } else {
            LOG_WARN("dath", "FromFdt failed: %d", frc);
        }
    }

    // ---- PCIe enumeration. Discovers the host bridge from the FDT
    //      and walks the bus; subsequent drivers (xHCI, NVMe, …)
    //      pick functions out of g_pci_inv via Croi_Pci_FindByClass.
    {
        int prc = Croi_Pci_Init(&g_pci_inv, &fdt);
        if (prc == CARA_EOK) {
            g_pci_inited = true;
        } else if (prc == CARA_ENOTFOUND) {
            LOG_INFO("pci ", "no pci-host-ecam-generic node; PCIe disabled");
        } else {
            LOG_WARN("pci ", "Croi_Pci_Init failed: %d", prc);
        }
    }

    // ---- xHCI host controller. First xHCI function gets probed and
    //      reset; later milestones bring up the Command/Event rings
    //      and walk PORTSC for connected devices.
    if (g_pci_inited) {
        u32 cursor = 0;
        const struct PciFunction *xfn = Croi_Pci_FindByClass(
            &g_pci_inv,
            PCI_CLASS_USB_XHCI_BASE,
            PCI_CLASS_USB_XHCI_SUB,
            PCI_CLASS_USB_XHCI_PROGIF,
            &cursor);
        if (xfn) {
            // Croi_Pci_FindByClass returned a const pointer into the
            // inventory; recover the index for Croi_Xhci_Probe (which
            // mutates the function record's bar[]).
            u32 fidx = (u32)(xfn - g_pci_inv.func);
            int xrc = Croi_Xhci_Probe(&g_xhci, &g_pci_inv, fidx);
            if (xrc == CARA_EOK) {
                g_xhci_probed = true;
                int src = Croi_Xhci_Setup(&g_xhci);
                if (src != CARA_EOK) {
                    LOG_WARN("xhci", "setup failed: %d", src);
                } else {
                    int prc = Croi_Xhci_PortsWalk(&g_xhci);
                    if (prc != CARA_EOK) {
                        LOG_WARN("xhci", "PortsWalk failed: %d", prc);
                    } else {
                        int arc = Croi_Xhci_AddressConnectedDevices(&g_xhci);
                        if (arc != CARA_EOK) {
                            LOG_WARN("xhci",
                                     "AddressConnectedDevices failed: %d", arc);
                        } else {
                            int drc = Croi_Xhci_ReadDescriptors(&g_xhci);
                            if (drc != CARA_EOK) {
                                LOG_WARN("xhci",
                                         "ReadDescriptors failed: %d", drc);
                            } else {
                                int crc = Croi_Xhci_ReadConfigurations(&g_xhci);
                                if (crc != CARA_EOK) {
                                    LOG_WARN("xhci",
                                             "ReadConfigurations failed: %d",
                                             crc);
                                }
                            }
                        }
                    }
                }
            } else {
                LOG_WARN("xhci", "probe failed: %d", xrc);
            }
        } else {
            LOG_INFO("xhci", "no xHCI controller in PCI inventory");
        }
    }

    // ---- Bring up the cooperative scheduler before running tests so
    //      the sched_smoke test can spawn workers and yield.
    Sched_Init();

    // ---- Construct exec.library.
    //      The library image lives in the .exec_lib section
    //      (croi.lds, VMA = 0x4000_0000). We hand Croi_MakeLibrary
    //      the kernel-side direct-map view of that region (since
    //      the kernel's PT doesn't map the user-VA), the generated
    //      vec table, and the V36+ version/revision/private-size.
    //      The library registers itself in the exec.library
    //      LibList; user-mode code reaches it via OpenLibrary
    //      starting in Phase D.
    {
        // First install the .exec_lib mapping in the boot PT so
        // kmain can read+write the user-VA 0x4000_0000 region.
        // (Croi_ExecLib_InstallMapping has already been wired into
        // every user task's PT in the spawn paths, but kmain itself
        // runs with the boot PT until it spawns user tasks.)
        if (Croi_ExecLib_InstallInBootPT() != CARA_EOK) {
            LOG_FATAL("entry", "InstallInBootPT(.exec_lib) failed");
            Croi_Halt();
        }

        // exec.library is linker-placed at user-VA 0x4000_0800.
        // Both kernel and user mode see this VA after the boot-PT
        // install above plus per-task PT install in spawn paths.
        struct Library *user_base =
            (struct Library *)CARA_EXEC_LIB_USER_BASE;
        struct TagItem mklib_tags[] = {
            { MKL_NAME,         (IPTR)"exec.library" },
            { MKL_BASE,         (IPTR)user_base },
            { MKL_VEC_TABLE,    (IPTR)exec_lib_vec },
            { MKL_VEC_COUNT,    (IPTR)exec_lib_vec_count },
            { MKL_VERSION,      36 },
            { MKL_REVISION,     0 },
            { MKL_PRIVATE_SIZE, (IPTR)Croi_ExecLib_PrivateSize() },
            { TAG_END,          0 },
        };
        struct Library *base = Croi_MakeLibrary(mklib_tags);
        if (!base) {
            LOG_FATAL("entry", "Croi_MakeLibrary(exec.library) failed");
            Croi_Halt();
        }
    }

    // ---- Run the in-kernel test suite. ----
    Test_RunAll();

    Croi_Halt();
}
